#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModelMotor, port2, motRight)
#pragma config(RenamedStdModelMotor, port3, motLeft)
#pragma config(RenamedStdModelMotor, port6, motArm)
#pragma config(RenamedStdModelSensor, in3, pmeter)
#pragma config(RenamedStdModelSensor, in4, lightSensor)
#pragma config(RenamedStdModelSensor, in6, accelrZ)
#pragma config(RenamedStdModelSensor, in7, accelrY)
#pragma config(RenamedStdModelSensor, in8, accelrX)
#pragma config(RenamedStdModelSensor, dgtl1, encodeRight)
#pragma config(RenamedStdModelSensor, dgtl3, encodeLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * Kevin Jiang
 * March 29 2019
 * Incorporate Functions
 * Guides the robot from Point A to the finish without crossing over any black lines.
 * Makes use of the motor encoders.
 */



/**
 * Sets the left and right motor encoders to zero.
 * Useful in movement methods for determining how far the robot moved.
 */
void resetEncoders(){
	
	SensorValue[encodeRight] = 0;
	SensorValue[encodeLeft] = 0;
}

/**
 * Sets the left and right motor speeds to 0 to stop it from moving.
 * Also has brief pause to lose any momentum it may have had.
 */
void stopMoving(){
	startMotor(motLeft, 0);
	startMotor(motRight, 0);
	wait1Msec(250);
}


/**
 * Moves the robot a certain distance.
 * The distance is in inches (since each little box is 3 inches on the scenarios, allows for easy programming)
 * The distance can be positive or negative, depending on direction
 */
void move(int dist){
	int modifier;

	// set the modifier for the motor power based on if the robot is supposed to go forwards or backwards.
	if(dist > 0){
		modifier = 1;
		} else {
		modifier = -1;
	}

	// distance can only be positive. Direction doesn't matter since it is already accounted for.
	dist = abs(dist);


	// convert distance in inches to the number of degrees the wheels must rotate.
	// based on the fact that the wheels have a circumference of 2.8cm
	float numDegreeRot = (360 / 6.926) * dist;

	// reset encoders to have a clean slate
	resetEncoders();

	// keep moving if any of the wheels haven't reached their rotation quota
	while(abs(SensorValue[encodeRight]) < abs(numDegreeRot) ||
		abs(SensorValue[encodeLeft]) < abs(numDegreeRot)){

		//left wheels
		if(abs(SensorValue[encodeRight]) < abs(numDegreeRot)) {
			startMotor(motLeft, 127 * modifier); //if the left wheels haven't reached their rotation quota, keep them rotating
			} else {
			stopMotor(motLeft); //if they have, stop the left wheels
		}

		//right wheels
		if(abs(SensorValue[encodeLeft]) < abs(numDegreeRot)) {
			startMotor(motRight, 127 * modifier); //if the right wheels haven't reached their rotation quota, keep them rotating
			} else {
			stopMotor(motRight); //if they have, stop the right wheels
		}
	}

	// stop the robot to prevent it from messing with proceeding methods.
	stopMoving();
}

void turn(char direction){
	resetEncoders();
	stopMoving();
	int modifier;



	wait1Msec(1200); // make sure robot is stopped
	const int numDegreeRot = 359;


	if(direction == 'l'){ //turn left
		modifier = -1;
		} else { // turn right
		modifier = 1;
	}
	resetEncoders();
	//do the actual moving
	while(abs(SensorValue[encodeRight]) < abs(numDegreeRot) ||
		abs(SensorValue[encodeLeft]) < abs(numDegreeRot)){
		//left wheels
		if(abs(SensorValue[encodeLeft]) < abs(numDegreeRot)) {
			startMotor(motLeft, 63 * modifier);
			} else {
			stopMotor(motLeft);
		}
		//right wheels
		if(abs(SensorValue[encodeRight]) < abs(numDegreeRot)) {
			startMotor(motRight, 63 * -1 * modifier);
			} else {
			motor[motRight] = 0;
		}

		wait1Msec(50);

	}
	stopMoving();
}

/**
 * get rid of useless arm that frequently goes over black lines/bumps into walls
 */
task getRidOfArm(){
	startMotor(motArm, -127);
	wait1Msec(1250);
	stopMotor(motArm);
}


task main()
{
	startTask(getRidOfArm); // get rid of useless arm
	move(16 * 3 +1); // move 16 squares + 1 inch
	turn('l'); // turn left
	move(6 * 3);// move 6 squares
	turn('l'); // turn left

	move(17 * 3); // move 17 squares
	turn('r'); // turn right
	move(6 * 3);// move 6 squares
	turn('r'); // turn right
	move(5 * 12 + 9);// move 5 feet and 9 inches
	wait10Msec(100); //wait a tiny bit of time to lose momentum
	turn('r');  // turn right
	move(3 * 12); // move 3 feet
	turn('l'); // turn left
	move(6 * 3);// move 6 squares
	turn('l'); // turn left
	move(3 * 12 - 2); // move 2 inches less than 3 feet. (34 inches)
}
