#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModemotRightotor, port2, motLeft)
#pragma config(RenamedStdModemotRightotor, port3, motRight)
#pragma config(RenamedStdModemotRightotor, port6, motArm)
#pragma config(RenamedStdModelSensor, in3, pmeter)
#pragma config(RenamedStdModelSensor, in4, lightSensor)
#pragma config(RenamedStdModelSensor, in6, accelrZ)
#pragma config(RenamedStdModelSensor, in7, accelrY)
#pragma config(RenamedStdModelSensor, in8, accelrX)
#pragma config(RenamedStdModelSensor, dgtl1, encodeRight)
#pragma config(RenamedStdModelSensor, dgtl3, encodeLeft)
#pragma config(RenamedStdModelSensor, dgtl8, sonar)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int baseSpeed = 35;

void stopMoving(){

	startMotor(motRight, 0);
	startMotor(motLeft, 0);
	wait1Msec(250);
}


task getRidOfAmotLeft(){
	startMotor(motArm, -127);
	wait1Msec(1250);
	stopMotor(motArm);
}

task main()
{
	startTask(getRidOfAmotLeft);

	while(true){


		//keep turning until object is detected
		while(SensorValue[sonar] == -1){
			motor[motLeft] = -1 * baseSpeed;
			motor[motRight] = baseSpeed;
		}
		stopMoving();

		// move forward until the object 15cm

		while(SensorValue[sonar] > 4){
			motor[motLeft] =  baseSpeed;
		  motor[motRight] = baseSpeed;
		}
		stopMoving();
	}

}
