#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModemotRightotor, port2, motLeft)
#pragma config(RenamedStdModemotRightotor, port3, motRight)
#pragma config(RenamedStdModemotRightotor, port6, motArm)
#pragma config(RenamedStdModelSensor, in3, pmeter)
#pragma config(RenamedStdModelSensor, in4, lightSensor)
#pragma config(RenamedStdModelSensor, in6, accelrZ)
#pragma config(RenamedStdModelSensor, in7, accelrY)
#pragma config(RenamedStdModelSensor, in8, accelrX)
#pragma config(RenamedStdModelSensor, dgtl1, encodeRight)
#pragma config(RenamedStdModelSensor, dgtl3, encodeLeft)
#pragma config(RenamedStdModelSensor, dgtl8, sonar)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * Kevin Jiang
 * March 29 2019
 * Speed of Sound
 * The robot moves forward towards the wall.
 * The robot's speed is set proportional to the distance from the wall.
 * Makes use of the sonar sensor.
 */


const int baseSpeed = 35;

/**
 * Sets the left and right motor speeds to 0
 */
void stopMoving(){
	startMotor(motRight, 0);
	startMotor(motLeft, 0);
	wait1Msec(250);
}

/**
 * Gets rid of the amotLeft since it isn't needed in this challenge
 */
task getRidOfAmotLeft(){
	startMotor(motArm, -127);
	wait1Msec(1250);
	stopMotor(motArm);
}

task main()
{
	startTask(getRidOfAmotLeft); //get rid of useless amotLeft

	//keep going forward until the ultrasonic sensor detects an object
	while(SensorValue[sonar] == -1){  
		motor[motLeft] = baseSpeed;
		motor[motRight] = baseSpeed;

	}

	// while the distance is >2cm, set the motor speed to be equal to the robot's distance from the object
	while(SensorValue[sonar] > 2){
		motor[motLeft] = SensorValue[sonar];
		motor[motRight] = SensorValue[sonar] ;
		wait1Msec(50);
	}

	// if it's less than 2cm, then stop the robot from moving
	stopMoving();

}
