#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModelMotor, port2, motRight)
#pragma config(RenamedStdModelMotor, port3, motLeft)
#pragma config(RenamedStdModelMotor, port6, motArm)
#pragma config(RenamedStdModelSensor, in3, pmeter)
#pragma config(RenamedStdModelSensor, in4, lightSensor)
#pragma config(RenamedStdModelSensor, in6, accelrZ)
#pragma config(RenamedStdModelSensor, in7, accelrY)
#pragma config(RenamedStdModelSensor, in8, accelrX)
#pragma config(RenamedStdModelSensor, dgtl1, encodeRight)
#pragma config(RenamedStdModelSensor, dgtl3, encodeLeft)
#pragma config(RenamedStdModelSensor, dgtl8, sonar)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int baseSpeed = 35;

/**
 * Sets the left and right motor speeds to 0
 */
void stopMoving(){
	startMotor(motLeft, 0);
	startMotor(motRight, 0);
	wait1Msec(250);
}

/**
 * Gets rid of the arm since it isn't needed in this challenge
 */
task getRidOfArm(){
	startMotor(motArm, -127);
	wait1Msec(1250);
	stopMotor(motArm);
}

task main()
{
	startTask(getRidOfArm); //get rid of useless arm

	//keep going forward until the ultrasonic sensor detects an object
	while(SensorValue[sonar] == -1){  
		motor[motRight] = baseSpeed;
		motor[motLeft] = baseSpeed;

	}

	// while the distance is >2cm, set the motor speed to be equal to the robot's distance from the object
	while(SensorValue[sonar] > 2){
		motor[motRight] = SensorValue[sonar];
		motor[motLeft] = SensorValue[sonar] ;
		wait1Msec(50);
	}

	// if it's less than 2cm, then stop the robot from moving
	stopMoving();

}
