#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModelMotor, port2, motRight)
#pragma config(RenamedStdModelMotor, port3, motLeft)
#pragma config(RenamedStdModelMotor, port6, motArm)
#pragma config(RenamedStdModelSensor, in3, pmeter)
#pragma config(RenamedStdModelSensor, in4, lightSensor)
#pragma config(RenamedStdModelSensor, in6, accelrZ)
#pragma config(RenamedStdModelSensor, in7, accelrY)
#pragma config(RenamedStdModelSensor, in8, accelrX)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move(int dist){
	int modifier;

	if(dist > 0){
		modifier = 1;
	} else {
		modifier = -1;
		dist *= -1;
	}

	while(dist > 0) {
		startMotor(motRight, 127 * modifier);
		startMotor(motLeft, 127 * modifier);
		wait1Msec(500);
		dist--;
	}

}


task main()
{
	for(int i = 0; i < 16; i += 4){
		move(i);
  	move(i * -1);

	}


}
