#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModelMotor, port2, motRight)
#pragma config(RenamedStdModelMotor, port3, motLeft)
#pragma config(RenamedStdModelMotor, port6, motArm)
#pragma config(RenamedStdModelSensor, in3, pmeter)
#pragma config(RenamedStdModelSensor, in4, lightSensor)
#pragma config(RenamedStdModelSensor, in6, accelrZ)
#pragma config(RenamedStdModelSensor, in7, accelrY)
#pragma config(RenamedStdModelSensor, in8, accelrX)
#pragma config(RenamedStdModelSensor, dgtl1, encodeRight)
#pragma config(RenamedStdModelSensor, dgtl3, encodeLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void whack(){
	startMotor(motArm, -127);
	wait1Msec(1500);
	startMotor(motArm, 127);
	wait1Msec(4000);
	startMotor(motArm, -127);
	wait1Msec(1500);
}

void resetEncoders(){
	//Reset encoder values to zero
	SensorValue[encodeRight] = 0;
	SensorValue[encodeLeft] = 0;
}

void stopMoving(){

	startMotor(motLeft, 0);
	startMotor(motRight, 0);
	wait1Msec(250);
}


//distance in inches
void move(int dist){
	int modifier;

	if(dist > 0){
		modifier = 1;
		} else {
		modifier = -1;
		dist *= -1;
	}

	/*
	//convert distance into number of rotations
	float numRot = dist / 6.926;
	//convert number of rotations into degrees
	int numDegreeRot = 360 * numRot;
*/
	float numDegreeRot = (360 / 6.926) * dist;


	resetEncoders();
	//do the actual moving
	while(abs(SensorValue[encodeRight]) < abs(numDegreeRot) ||
		abs(SensorValue[encodeLeft]) < abs(numDegreeRot)){



		//left wheels
		if(abs(SensorValue[encodeRight]) < abs(numDegreeRot)) {
			startMotor(motLeft, 127 * modifier);
			} else {
			stopMotor(motLeft);
		}
		//right wheels
		if(abs(SensorValue[encodeLeft]) < abs(numDegreeRot)) {
			startMotor(motRight, 127 * modifier);
			} else {
			stopMotor(motRight);
		}

	}
	stopMoving();
}

void turn(char direction){
	resetEncoders();
	stopMoving();
	int modifier;



	wait1Msec(1200); // make sure robot is stopped
	const int numDegreeRot = 359;


	if(direction == 'l'){ //turn left
		modifier = -1;
		} else { // turn right
		modifier = 1;
	}
	resetEncoders();
	//do the actual moving
	while(abs(SensorValue[encodeRight]) < abs(numDegreeRot) ||
		abs(SensorValue[encodeLeft]) < abs(numDegreeRot)){
		//left wheels
		if(abs(SensorValue[encodeLeft]) < abs(numDegreeRot)) {
			startMotor(motLeft, 63 * modifier);
			} else {
			stopMotor(motLeft);
		}
		//right wheels
		if(abs(SensorValue[encodeRight]) < abs(numDegreeRot)) {
			startMotor(motRight, 63 * -1 * modifier);
			} else {
			motor[motRight] = 0;
		}

		wait1Msec(50);

	}
	stopMoving();
}


task getRidOfArm(){
	startMotor(motArm, -127);
	wait1Msec(1250);
	stopMotor(motArm);
}


task main()
{

	startTask(getRidOfArm);
	move(16 * 3 +1);
	turn('l');
	move(6 * 3);//vertical
	turn('l');

	move(17 * 3); //middle left
	turn('r');
	move(6 * 3);//vertical
	turn('r');
	move(5 * 12 + 9);//top going right
	wait10Msec(100);
	turn('r');
	move(3 * 12); //vertical down
	turn('l');
	move(6 * 3);// tiny bit before finish
	turn('l');
	move(3 * 12 - 2); //vertical to finish
}
