#pragma config(Sensor, in1,    midLine,        sensorAnalog)
#pragma config(Sensor, dgtl11, rightTouch,     sensorTouch)
#pragma config(Sensor, dgtl12, leftTouch,      sensorNone)
#pragma config(Motor,  port1,           motRight,      tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port10,          motLeft,       tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
