#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in2,    midLine,        sensorLineFollower)
#pragma config(Sensor, in3,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           motRight,      tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           motLeft,       tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           motArm,        tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(DatalogSeries, 0, "LeftFollow", Sensors, Sensor, in1, 50)
#pragma config(DatalogSeries, 1, "MidFollow", Sensors, Sensor, in2, 50)
#pragma config(DatalogSeries, 2, "RightFollow", Sensors, Sensor, in3, 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stopMoving(){

	startMotor(motLeft, 0);
	startMotor(motRight, 0);
	wait1Msec(250);
}


task getRidOfArm(){
	startMotor(motArm, -127);
	wait1Msec(1250);
	stopMotor(motArm);
}


int jitter(tMotor mPrimary, tMotor mSecondary, int jitterTime){
	const int speed = 63;
	startMotor(mPrimary, speed);
	startMotor(mSecondary, -1 * speed);
	wait1Msec(jitterTime / 2);
	stopMotor(mPrimary);
	stopMoving();
	int sensorReading = SensorValue[midLine];
	startMotor(mPrimary, -1 * speed);
	startMotor(mSecondary, speed);
	wait1Msec(jitterTime / 2);
	stopMoving();
	datalogAddValueWithTimeStamp(0, sensorReading);
	return sensorReading;
}



task main()
{
	const int timePerJitter = 100;
	startTask(getRidOfArm);
	while(true){
		//Plan
		//Jitter both ways, figure out which returns the more +ve, number, then only move in that direction(using only 1 motor)
		int leftReading, rightReading;
		leftReading = jitter(motRight, motLeft, timePerJitter);

		rightReading = jitter(motLeft, motRight, timePerJitter);
		tMotor toMove;
		if(leftReading > rightReading){
			toMove = motRight;
		} else {
			toMove = motLeft;
		}
		startMotor(toMove, 100);
		wait1Msec(timePerJitter * 3/4);
		stopMotor(toMove);
		wait1Msec(50);


	}
}
