#pragma config(UserModel, "C:/Users/Kevin J/Documents/randomGithub/TEJ4M-RobotC-Programs/PhysicalNamingScheme.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void setMotors(int motLeftLvl, int motRightLvl) {
	motor[motLeft] = motLeftLvl;
	motor[motRight] = motRightLvl;
}

void turn(char direction){
	int modifier;

	if(direction == 'l'){ //turn left
		modifier = -1;
		} else { // turn right
		modifier = 1;
	}

	wait1Msec(1500); // make sure robot is stopped

	motor[motRight] = 64 * modifier;
	motor[motLeft] = -1 * 64 * modifier;

	wait1Msec(1250);
	stopMoving();
}



task main()
{
	for(int i = 0; i< 4; i++ {

		while(SensorValue[leftTouch] != 1 && SensorValue[rightTouch] != 1) {
			setMotors(155, 155);
		}

		setMotors(-155, -155);
		wait1Msec(500);
		turn('r');

		wait1Msec(1000);
	}


}
