#pragma config(Sensor, in7,    irSense,        sensorReflection)
#pragma config(Sensor, in8,    midLine,        sensorReflection)
#pragma config(Sensor, dgtl11, rightTouch,     sensorTouch)
#pragma config(Sensor, dgtl12, leftTouch,      sensorTouch)
#pragma config(Motor,  port1,           motRight,      tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port10,          motLeft,       tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int BLACK = 600; //anything >500 is blacc
#define bp 60 //base power
#define W 100 //wait time (ms)

int recentBumps = 0;

void stopMoving() {
	motor[motLeft] = 0;
	motor[motRight] = 0;
}

void setMotors(int motLeftLvl, int motRightLvl) {
	motor[motLeft] = motLeftLvl;
	motor[motRight] = motRightLvl;
}

task uwu() {
	while(true) {
		wait1Msec(400);
		if(recentBumps > 0) //constantly subtract on a timer
				--recentBumps;
		
		if(recentBumps > 5){
			int startTime = time100[];
			int endTime = startTime + 5;
			while(time100[] < endTime) {
				setMotors(-bp, -bp); //move back	
			}
			stopMoving();//yeet yote yodel
		}	
	}
}



task main()
{
	startTask(uwu);
	while(true){
		while(SensorValue[midLine] > BLACK) {//turn left
			setMotors(-bp, bp);
		}
		bool leftGood = false, rightGood = false;
		//checkleft
		setMotors(-bp, bp);
		wait1Msec(70);
		stopMoving(); 
		wait1Msec(70);
		if(SensorValue[midLine] < BLACK) {
		leftGood = true;}


		//checkRight
		setMotors(bp, -bp);//revert
		wait1Msec(W);
		stopMoving(); 
		wait1Msec(W);
		setMotors(bp, -bp);//move right
		wait1Msec(W);
		stopMoving(); 
		wait1Msec(W);
			if(SensorValue[midLine] > BLACK) {
		rightGood = true;}


		setMotors(-bp, bp);//revert
		wait1Msec(W);

		if(leftGood && rightGood) {//move forward
			setMotors(bp, bp);
			wait1Msec(W);
		} else if(leftGood && !rightGood) { //turn a tiny bit right
			setMotors(bp, -bp);
			wait1Msec(W/2);
		} else if(!leftGood && rightGood) {//turn left a tiny bit
			setMotors(-bp, bp);
			wait1Msec(W/2);
		} else { //ya done failed
			//turn left until you hit black
					while(SensorValue[midLine] > BLACK) {//turn left
						setMotors(-bp, bp);

						}
						wait1Msec(10);
		}
		
		++recentBumps;


	}

}
