#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModemotRightotor, port2, motLeft)
#pragma config(RenamedStdModemotRightotor, port3, motRight)
#pragma config(RenamedStdModemotRightotor, port6, motArm)
#pragma config(RenamedStdModelSensor, in3, pmeter)
#pragma config(RenamedStdModelSensor, in4, lightSensor)
#pragma config(RenamedStdModelSensor, in6, accelrZ)
#pragma config(RenamedStdModelSensor, in7, accelrY)
#pragma config(RenamedStdModelSensor, in8, accelrX)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void stopMotors(){

	startMotor(motRight, 0);
	startMotor(motLeft, 0);
}

void move(int dist){
	int modifier;

	if(dist > 0){
		modifier = 1;
	} else {
		modifier = -1;
		dist *= -1;
	}

	while(dist > 0) {
		startMotor(motLeft, 127 * modifier);
		startMotor(motRight, 127 * modifier);
		wait1Msec(610);
		dist--;
	}
	stopMotors();
}

void turn(char direction){
	int modifier;

	if(direction == 'l'){ //turn left
	 	modifier = -1;
	} else { // turn right
		modifier = 1;
	}

	wait1Msec(1500); // make sure robot is stopped

	startMotor(motRight, 64 * modifier);
	startMotor(motLeft, 64 * -1 * modifier);
	wait1Msec(1250);
	stopMotors();
}



task main()
{
	startMotor(motArm, -127);
	wait1Msec(1250);
	stopMotor(motArm);
	move(5);
	turn('l');
	move(5);
	turn('r');
	move(3);
	startMotor(motRight, -90);
	startMotor(motLeft, -90);
	wait1Msec(600);
	stopMotors();
	//turn right
	startMotor(motRight, 100);
	wait1Msec(800);
	startMotor(motLeft, -50);
	wait1Msec(600);
	stopMotors();
	wait1Msec(500);

	move(2);



}
