#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModelMotor, port2, motRight)
#pragma config(RenamedStdModelMotor, port3, motLeft)
#pragma config(RenamedStdModelMotor, port6, motArm)
#pragma config(RenamedStdModelSensor, in3, pmeter)
#pragma config(RenamedStdModelSensor, in4, lightSensor)
#pragma config(RenamedStdModelSensor, in6, accelrZ)
#pragma config(RenamedStdModelSensor, in7, accelrY)
#pragma config(RenamedStdModelSensor, in8, accelrX)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void stopMoving(){

	startMotor(motLeft, 0);
	startMotor(motRight, 0);
}

void move(int dist){
	int modifier;

	if(dist > 0){
		modifier = 1;
		} else {
		modifier = -1;
		dist *= -1;
	}

	while(dist > 0) {
		startMotor(motRight, 127 * modifier);
		startMotor(motLeft, 127 * modifier);
		wait1Msec(580);
		dist--;
	}
	stopMoving();
}

void turn(char direction){
	int modifier;

	if(direction == 'l'){ //turn left
		modifier = -1;
		} else { // turn right
		modifier = 1;
	}

	wait1Msec(1500); // make sure robot is stopped

	startMotor(motLeft, 64 * modifier);
	startMotor(motRight, 64 * -1 * modifier);
	wait1Msec(1250);
	stopMoving();
}



task main()
{
	for(int i = 0; i < 8; i++){
		move(6);
		turn('r');
	}


}
