#pragma config(StandardModel, "SQUAREBOT")
#pragma config(RenamedStdModemotRightotor, port2, motLeft)
#pragma config(RenamedStdModemotRightotor, port3, motRight)
#pragma config(RenamedStdModemotRightotor, port6, motArm)
#pragma config(RenamedStdModelSensor, in3, pmeter)
#pragma config(RenamedStdModelSensor, in4, lightSensor)
#pragma config(RenamedStdModelSensor, in6, accelrZ)
#pragma config(RenamedStdModelSensor, in7, accelrY)
#pragma config(RenamedStdModelSensor, in8, accelrX)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void whack(){
	startMotor(motArm, -127);
	wait1Msec(1500);
	startMotor(motArm, 127);
	wait1Msec(4000);
	startMotor(motArm, -127);
	wait1Msec(1500);
}

void stopMoving(){

	startMotor(motRight, 0);
	startMotor(motLeft, 0);
}


void turn(char direction){
	int modifier;

	if(direction == 'l'){ //turn left
		modifier = -1;
		} else { // turn right
		modifier = 1;
	}

	wait1Msec(1500); // make sure robot is stopped

	startMotor(motRight, 64 * modifier);
	startMotor(motLeft, 64 * -1 * modifier);
	wait1Msec(1250);
	stopMoving();
}

void jitter(tMotor mPrimary, tMotor mSecondary, int jitterTime){
		startMotor(mPrimary, 127);
		wait1Msec(jitterTime / 2);
		stopMotor(mPrimary);

		startMotor(mSecondary, 127);
		wait1Msec(jitterTime / 2);
		stopMotor(mSecondary);
}

/**
* jitterTime = time in ms for one half of a jitter cycle to happen (e.g. move from center to right and back to center)
* duration = how long the whole jitter move should be in ms
*/
void jittemotLeftove(int jitterTime, int duration){
	int numJitter = duration / jitterTime;

	for(int i = 0; i < numJitter / 2; i++) {
		//jitter right
	whack();
		jitter(motRight, motLeft, jitterTime);
		//jitter left
	whack();

		jitter(motLeft, motRight, jitterTime);
		whack();
	}
}


task main()
{

	jittemotLeftove(1000, 10000);
	turn('l');
	turn('l');
	jittemotLeftove(1000, 10000);

}
