#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in2,    midLine,        sensorLineFollower)
#pragma config(Sensor, in3,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in4,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encodeRight,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encodeLeft,     sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           motRight,      tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           motLeft,       tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           motArm,        tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(DatalogSeries, 0, "LeftFollow", Sensors, Sensor, in1, 50)
#pragma config(DatalogSeries, 1, "MidFollow", Sensors, Sensor, in2, 50)
#pragma config(DatalogSeries, 2, "RightFollow", Sensors, Sensor, in3, 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int baseSpeed = 120;
const int turnSpeed = 35;
const int waitTime = 50; //waiting between sensor checks
const int restTime = 1000;//rest time in between commands


task getRidOfArm(){
	startMotor(motArm, -127);
	wait1Msec(1250);
	stopMotor(motArm);
}



void resetEncoders(){
	//Reset encoder values to zero
	SensorValue[encodeRight] = 0;
	SensorValue[encodeLeft] = 0;
}

void stopMoving(){

	startMotor(motLeft, 0);
	startMotor(motRight, 0);
}


//distance in inches
void move(int dist){
	int modifier;

	if(dist > 0){
		modifier = 1;
		} else {
		modifier = -1;
		dist = abs(dist);
	}
	/*
	//convert distance into number of rotations
	float numRot = dist / 6.926;
	//convert number of rotations into degrees
	int numDegreeRot = 360 * numRot;
	*/
	float numDegreeRot = (360 / 6.926) * dist;


	resetEncoders();
	//do the actual moving
	while(abs(SensorValue[encodeRight]) < abs(numDegreeRot) ||
		abs(SensorValue[encodeLeft]) < abs(numDegreeRot)){


		//left wheels
		if(abs(SensorValue[encodeRight]) < abs(numDegreeRot)) {
			startMotor(motLeft, 127 * modifier);
			} else {
			stopMotor(motLeft);
		}
		//right wheels
		if(abs(SensorValue[encodeLeft]) < abs(numDegreeRot)) {
			startMotor(motRight, 127 * modifier);
			} else {
			stopMotor(motRight);
		}


	}
	stopMoving();
}

void turn(char direction){
	resetEncoders();
	stopMoving();
	int modifier;



	wait1Msec(1200); // make sure robot is stopped
	int numDegreeRot = 361;


	if(direction == 'l'){ //turn left
		modifier = -1;
		} else { // turn right
		modifier = 1;
	}
	resetEncoders();
	//do the actual moving
	while(abs(SensorValue[encodeRight]) < abs(numDegreeRot) ||
		abs(SensorValue[encodeLeft]) < abs(numDegreeRot)){


		//left wheels
		if(abs(SensorValue[encodeLeft]) < abs(numDegreeRot)) {
			startMotor(motLeft, 63 * modifier);
			} else {
			stopMotor(motLeft);
		}
		//right wheels
		if(abs(SensorValue[encodeRight]) < abs(numDegreeRot)) {
			startMotor(motRight, 63 * -1 * modifier);
			} else {
			motor[motRight] = 0;

		}
		wait1Msec(50);

	}
	stopMoving();
}

void setMotors(tMotor m0, tMotor m1, int lvl){
	motor[m0] = lvl;
	motor[m1] = lvl;
}

//void setMotors(int lvl){
//	motor[motLeft] = lvl;
//	motor[motRight] = lvl;
//}

//Keeps the bot moving forward until
void forwardUntilBigEnough(tMotor m1, tMotor m2, tSensors sensor, int desiredVal){

	while(SensorValue[sensor] < desiredVal){
		setMotors(m1, m2, baseSpeed);
		wait1Msec(waitTime);
	}
	setMotors(m1, m2, 0);
}

void forwardUntilSmallEnough(tMotor m1, tMotor m2, tSensors sensor, int desiredVal){

	while(SensorValue[sensor] > desiredVal && SensorValue[sensor] != -1){
		setMotors(m1, m2, baseSpeed);
		wait1Msec(waitTime);
	}
	setMotors(m1, m2, 0);


}



//turns until the robot is facing its original direction
void turnUntilReset(){
	const int turnTolerance = 2;//.2degree each way

	while(abs(SensorValue[gyro] % 3600) > turnTolerance ){
		motor[motRight] = -1 * turnSpeed;
		motor[motLeft] = turnSpeed;

	}

	stopMoving();
}


//turns until the robot is facing its original direction
//DO NOT Use when degreesHeading == 0 (actually I should squish the 2 funcitons together someitme)
void setHeading(int degreesHeading){
	const int turnTolerance = 2;//.2 degrees each way

	while(abs(SensorValue[gyro] / 10 - degreesHeading) > turnTolerance ){
		motor[motRight] = -1 * turnSpeed;
		motor[motLeft] = turnSpeed;
		wait1Msec(100);

	}
	setMotors(motLeft, motRight, 0);

	stopMoving();
}



void setMotorToPos(tMotor m1, tSensors pot, int desiredEncoderPos){
	//make sure that it's moving the right way
	int direction = -1; // by default, move downwards
	if(SensorValue[pot] < desiredEncoderPos) { // means want to move it upwards (relative to starting position)
		direction = 1;
	}

	//get it so that it is within 10 steps of desired outcome
	while(abs(SensorValue[pot] - desiredEncoderPos) > 50 / 2) {
		motor[m1] = direction * turnSpeed;	//use turnspeed since it's slower (should be more accurate)
	}
	motor[m1] = 0; //stop the motor once it's at the right position

}


int jitter(tMotor mPrimary, tMotor mSecondary, int jitterTime){
	const int speed = 63;
	startMotor(mPrimary, speed);
	startMotor(mSecondary, -1 * speed);
	wait1Msec(jitterTime / 2);
	stopMotor(mPrimary);
	stopMoving();
	int sensorReading = SensorValue[midLine];
	startMotor(mPrimary, -1 * speed);
	startMotor(mSecondary, speed);
	wait1Msec(jitterTime / 2);
	stopMoving();
	datalogAddValueWithTimeStamp(0, sensorReading);
	return sensorReading;
}


void actualJitterMove(tMotor m1, tMotor m2, int timePerJitter){
	int leftReading, rightReading;
	leftReading = jitter(m1, m2, timePerJitter);

	rightReading = jitter(m1, m2, timePerJitter);
	tMotor toMove;
	if(leftReading > rightReading){
		toMove = m2;
		} else {
		toMove = m1;
	}

	motor[toMove] = baseSpeed;
	wait1Msec(timePerJitter * 3/4);
	stopMotor(toMove);
	wait1Msec(50);
}


void jitterUntilSmallEnough(tMotor m1, tMotor m2, tSensors sensor, int desiredVal){
	const int TIMEPERJITTER = 160; //160ms
	while(SensorValue[sensor] > desiredVal && SensorValue[sensor] != -1){
		actualJitterMove(m1, m2, TIMEPERJITTER);
	}
	setMotors(m1, m2, 0);


}




//////////////////////////////////////
////////////////////////////////////
task main() {

	//constants for sensor value benchmarks
	const int HORIZONTAL = 3240, //moves the arm into a horizontal position
						DIAGONAL = 2100,//moves arm ~45 degrees above horizontal
						ALLDOWN = 4095,  //arm rotation poteniometer for putting the arm as far down as possible

						BLACK = 1800,
						PICKUPRANGE = 9;//light sensor showing black line





	//	TODO
	//
	//Start from A
	//
	//Grab the first blue ball
	//
	//Deposit in the center hoop
	//
	//Turn, and continue forward (turnuntilreset)
	//
	//Forward, forward etc. until reach semicircle
	//
	//Follow the semicirlcle Until point A
	//
	//Go forward until the "start" aka turn left
	//Follow the resulting arrows until you reach the end box
	//Stop. END.


	move(4);//move cross the starting line
	forwardUntilBigEnough(motLeft, motRight, midLine, BLACK);//move forward to the first line with the ball
	move(2);//center the robot
	wait1Msec(restTime);
	setHeading(90);
	wait1Msec(restTime);
	forwardUntilSmallEnough(motLeft, motRight, sonar, PICKUPRANGE); //move close enough to pole to pick up
	setMotorToPos(motArm, armPot, DIAGONAL);//pickup the ball
	move(-6);//move 6 inches back
	turnUntilReset();//reset heading



	//move across 3 lines
	for(int i = 0; i < 3; i++){
		move(4);//move across that black line
		forwardUntilBigEnough(motLeft, motRight, midLine, BLACK);
	}
	//deposit ball in hoop
	wait1Msec(restTime);
	setHeading(90);
	wait1Msec(restTime);
	forwardUntilSmallEnough(motLeft, motRight, sonar, PICKUPRANGE); //move close enough to pole to pick up
	setMotorToPos(motArm, armPot, HORIZONTAL);//drop the ball
	wait1Msec(2500);//wait for ball to drop
	motor[motArm] = -127;
	wait1Msec(2500);//wait for arm to retract
	motor[motArm] = 0;
	move(-6);//move 6 inches back
	turnUntilReset();//reset heading


	//move across 5 lines
	for(int i = 0; i < 5; i++){
		forwardUntilBigEnough(motLeft, motRight, midLine, BLACK);
	}

	jitterUntilSmallEnough(motLeft, motRight, sonar, 15);//follow line until robot is roughly 6 inches away from wall
	turnUntilReset();//reset heading
	move(5);//move across the 1st line

	//move across 5 lines
	for(int i = 0; i < 4; i++){
		forwardUntilBigEnough(motLeft, motRight, midLine, BLACK);
	}

	setHeading(270);//turn left


	wait(9999);



}
